{"uuid": "23adbc23-020e-4e64-8f37-4529ecc7a959", "children": ["1a3ac4a0-f85b-475d-9fa0-e8b37c27458b"], "befores": [{"name": "test_item_next", "status": "broken", "statusDetails": {"message": "requests.exceptions.SSLError: HTTPSConnectionPool(host='testapi.pookie.com.cn', port=443): Max retries exceeded with url: /item/mbox/378/next/v5?first_random=True (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))\n", "trace": "  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/testcases/api_test/test_07_item.py\", line 38, in test_item_next\n    result = item_next_true(item_id, first_random)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/operation/item.py\", line 21, in item_next_true\n    res = item.item_next(item_id=item_id, headers=headers, params=params)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/api/item.py\", line 18, in item_next\n    return self.get(\"/item/mbox/{}/next/v5\".format(item_id), **kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/core/rest_client.py\", line 13, in get\n    return self.request(url, \"GET\", **kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/core/rest_client.py\", line 35, in request\n    return self.session.get(url, **kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/requests/sessions.py\", line 537, in get\n    return self.request('GET', url, **kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/requests/sessions.py\", line 524, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/requests/sessions.py\", line 637, in send\n    r = adapter.send(request, **kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/requests/adapters.py\", line 514, in send\n    raise SSLError(e, request=request)\n"}, "steps": [{"name": "步骤1：下一个盲盒详情", "status": "passed", "start": 1632741471680, "stop": 1632741471680}], "start": 1632741471680, "stop": 1632741471762}], "start": 1632741471680, "stop": 1632741472267}