{"uuid": "0910d749-7e7d-4dcc-bf9b-0903dc8e8865", "children": ["47393edb-ca86-475b-b441-5016749dfdb1"], "befores": [{"name": "test_item_status", "status": "broken", "statusDetails": {"message": "requests.exceptions.SSLError: HTTPSConnectionPool(host='testapi.pookie.com.cn', port=443): Max retries exceeded with url: /item/mbox/cell_status?first_random=false&item_id=378&box_no= (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))\n", "trace": "  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/testcases/api_test/test_07_item.py\", line 71, in test_item_status\n    result = item_status(item_id, box_no)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/operation/item.py\", line 25, in item_status\n    res = item.item_status(item_id=item_id, box_no=box_no, headers=headers)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/api/item.py\", line 22, in item_status\n    **kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/core/rest_client.py\", line 13, in get\n    return self.request(url, \"GET\", **kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/core/rest_client.py\", line 35, in request\n    return self.session.get(url, **kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/requests/sessions.py\", line 537, in get\n    return self.request('GET', url, **kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/requests/sessions.py\", line 524, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/requests/sessions.py\", line 637, in send\n    r = adapter.send(request, **kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/requests/adapters.py\", line 514, in send\n    raise SSLError(e, request=request)\n"}, "steps": [{"name": "步骤2：盲盒的最新状态", "status": "passed", "start": 1639030920015, "stop": 1639030920015}], "start": 1639030920015, "stop": 1639030920083}], "start": 1639030920015, "stop": 1639030920293}