{"uuid": "88e346e6-47aa-4708-929f-edc87c95097f", "children": ["ef78fdb5-7f37-4818-be16-d5de849985ec"], "befores": [{"name": "test_item_status", "status": "failed", "statusDetails": {"message": "AssertionError: 接口的返回码：【-1】，接口返回的信息：user.error.no_login\nassert False is True\n +  where False = <class 'core.result_base.ResultBase'>.success\n", "trace": "  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/testcases/api_test/test_07_item.py\", line 71, in test_item_status\n    assert result.success is True, result.error\n"}, "steps": [{"name": "步骤2：盲盒的最新状态", "status": "passed", "start": 1648188196456, "stop": 1648188196456}], "start": 1648188196456, "stop": 1648188196482}], "start": 1648188196456, "stop": 1648188196569}