{"name": "test_init_wx[phone0]", "status": "broken", "statusDetails": {"message": "pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '13656642042']'' at line 1\")", "trace": "self = <testcases.init_test.test_init_phone.TestInitPhone object at 0x10b12c630>\nphone = ['13656642042']\n\n    @pytest.mark.parametrize(\"phone\", api_data[\"test_init_wx\"])\n    def test_init_wx(self, phone):\n        \"\"\"初始化手机号为新用户\"\"\"\n        sql = \"select id as user_id from user where phone ='%s' \" % phone\n>       data = db.select_db(sql)\n\ntest_init_phone.py:14: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../common/mysql_operate.py:38: in select_db\n    self.cur.execute(sql)\n../../venv/lib/python3.7/site-packages/pymysql/cursors.py:170: in execute\n    result = self._query(query)\n../../venv/lib/python3.7/site-packages/pymysql/cursors.py:328: in _query\n    conn.query(q)\n../../venv/lib/python3.7/site-packages/pymysql/connections.py:517: in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n../../venv/lib/python3.7/site-packages/pymysql/connections.py:732: in _read_query_result\n    result.read()\n../../venv/lib/python3.7/site-packages/pymysql/connections.py:1075: in read\n    first_packet = self.connection._read_packet()\n../../venv/lib/python3.7/site-packages/pymysql/connections.py:684: in _read_packet\n    packet.check_error()\n../../venv/lib/python3.7/site-packages/pymysql/protocol.py:220: in check_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndata = b\"\\xff(\\x04#42000You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '13656642042']'' at line 1\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack('<h', data[1:3])[0]\n        is_41 = data[3:4] == b\"#\"\n        if is_41:\n            # client protocol 4.1\n            errval = data[9:].decode('utf-8', 'replace')\n        else:\n            errval = data[3:].decode('utf-8', 'replace')\n        errorclass = error_map.get(errno, InternalError)\n>       raise errorclass(errno, errval)\nE       pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '13656642042']'' at line 1\")\n\n../../venv/lib/python3.7/site-packages/pymysql/err.py:109: ProgrammingError"}, "description": "初始化手机号为新用户", "parameters": [{"name": "phone", "value": "['13656642042']"}], "start": 1635757287506, "stop": 1635757287596, "uuid": "ccf1d3a9-e841-4bdb-a46a-26f419b68f18", "historyId": "b19b12ca8034f60805638b6cb5bcf097", "testCaseId": "314b4765a31164db261c4e994766b604", "fullName": "testcases.init_test.test_init_phone.TestInitPhone#test_init_wx", "labels": [{"name": "parentSuite", "value": "testcases.init_test"}, {"name": "suite", "value": "test_init_phone"}, {"name": "subSuite", "value": "TestInitPhone"}, {"name": "host", "value": "tongchunyan.local"}, {"name": "thread", "value": "22102-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.init_test.test_init_phone"}]}