{"name": "test_refund", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'ResultBase' has no attribute 'erraor'", "trace": "self = <testcases.admin_test.test_refund_00001.TestAdminRefund object at 0x10468a518>\n\n    def test_refund(self):\n        sql = \"select order_no from user_order where user_id in('1340') and\" \\\n              \" status not in(0,30,31,300) and real_price >= 0.1 limit 5 \"\n        data = db.select_db(sql)\n        logger.info(\"data===>{}\".format(data))\n        for i in range(len(data)):\n            logger.info(data[i][\"order_no\"])\n            order_no = data[i][\"order_no\"]\n            logger.info(\"*************** 开始执行用例 *************** /n\")\n            result = refund_admin(order_no)\n>           assert result.success is True, result.erraor\nE           AttributeError: type object 'ResultBase' has no attribute 'erraor'\n\ntest_refund_00001.py:19: AttributeError"}, "attachments": [{"name": "log", "source": "61ea806b-8ff2-4912-9f4d-5c4f656f8f94-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "5f514fc0-b329-46be-bc5b-937929a2765e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "4b8a4b3e-ebc4-4d3e-b609-b961a5064ca5-attachment.txt", "type": "text/plain"}], "start": 1635909537828, "stop": 1635909537981, "uuid": "3705634b-befc-4770-bc55-fe8261abb76e", "historyId": "a0a6875d0f15aa537f9fb7f8ef19067b", "testCaseId": "392cae74f4aea4f9774e5ed6ec104378", "fullName": "testcases.admin_test.test_refund_00001.TestAdminRefund#test_refund", "labels": [{"name": "parentSuite", "value": "testcases.admin_test"}, {"name": "suite", "value": "test_refund_00001"}, {"name": "subSuite", "value": "TestAdminRefund"}, {"name": "host", "value": "tongchunyan.local"}, {"name": "thread", "value": "39226-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.admin_test.test_refund_00001"}]}